version: "3.3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: loubou97
      MONGO_INITDB_ROOT_PASSWORD: loubou97

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: loubou97
      ME_CONFIG_MONGODB_ADMINPASSWORD: loubou97
  web:
    image: "loubou97/noteapp:latest"
    links:
      - mongo
    ports:
      - "8080:3000"
    environment:
      LOG_LEVEL: info
      PORT: 3000
      NODE_ENV: prod
      MONGO_USERNAME: loubou97
      MONGO_PASSWORD: loubou97
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_DB: admin
