kind: Deployment
apiVersion: apps/v1
metadata:
  name: noteapp-api
spec:
  replicas: 1
  selector:
      matchLabels:
          app: noteapp
          role: api
          env: production
  template:
    metadata:
      name: api
      labels:
        app: noteapp
        role: api
        env: production
    spec:
      containers:
      - name: api
        image: $DOCKER_IMAGE_URL:$VERSION
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "prod"
        - name: LOG_LEVEL
          value: "info"
        - name: PORT
          value: "3000"
        - name: MONGO_USERNAME
          value: "loubou97_admin"
        - name: MONGO_PASSWORD
          value: "$MONGO_PASSWORD"
        - name: MONGO_HOSTNAME
          value: "mongodb-loubou97.alwaysdata.net"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "loubou97_notesdb"
        ports:
        - name: api
          containerPort: 3000
      imagePullSecrets:
        - name: regcred