kind: Service
apiVersion: v1
metadata:
  name: noteapp-api
spec:
  ports:
  - name: api
    type: LoadBalancer
    port: 8080
    targetPort: 3000
    protocol: TCP
  selector:
    role: api
    app: noteapp