kind: Service
apiVersion: $VERSION
metadata:
  name: noteapp-api
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 8080
    targetPort: 3000
    protocol: TCP
  selector:
    role: api
    app: noteapp