
name: CD

on:  workflow_dispatch
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [approveapp]
    steps:
      - uses: actions/checkout@master
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
            resource-group: 'AKS-ressources'
            cluster-name: 'insat'
        
      - uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
           k8s/prod/api-deployment.yaml
           k8s/services/api.yaml

          images: 'loubou97/noteapp:latest'
          kubectl-version: 'latest'

  approveapp:
    runs-on: ubuntu-latest
    environment: akspromotion
    steps:
      - run: echo asked for approval
