name: CI/CD

on: [pull_request,push]
env:
  LOG_LEVEL: info
  PORT: 3000
  NODE_ENV: test
  MONGO_DB: loubou97_notesdb
  DOCKER_IMAGE_NAME: loubou97/noteapp
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  DOCKER_IMAGE_TAG: latest
jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy to k8s
    steps:
      - name: Deploy
        uses: danielr1996/kubectl-action@1.0.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f ./k8s/prod/deployment.yaml
