name: Deploy
on:
  registry_package:
    types: [published]
  workflow_dispatch:
    branches: main
env:
  DOCKER_IMAGE_URL: docker.pkg.github.com/yousseff97/noteapp/noteapp
  DOCKER_IMAGE_PULL_SECRET: regcred
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pozetroninc/github-action-get-latest-release@master
        id: noteapp
        with:  
            repository: ${{ github.repository }}
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
            resource-group: 'AKS-ressources'
            cluster-name: 'insat'

      - uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{env.NAMESPACE}}
          manifests: |
           k8s/prod/api-deployment.yaml
           k8s/services/api.yaml
          Images: ${{env.DOCKER_IMAGE_URL}}:${{steps.noteapp.outputs.release}}
          imagepullsecrets: |
           ${{env.DOCKER_IMAGE_PULL_SECRET}}
          kubectl-version: 'latest'