name: Release

on:
  push:
    branches:
      - main
env:
  LOG_LEVEL: info
  PORT: 3000
  MONGO_DB: loubou97_notesdb

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run compile --if-present
      - run: npm run test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
