name: Staging deployment

on: [pull_request,push]
env:
  DOCKER_IMAGE_NAME: yousseff97/noteapp
  IMAGE_REGISTRY_URL: docker.pkg.github.com
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: npm install & build
          run: |
            npm install
            npm run compile
        - uses: actions/upload-artifact@master
          with:
            name: dist aritiact
            path: dist/
  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Build image and store in Github Packages
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: download artifact
        uses: actions/download-artifact@master
        with:
            name: dist aritiact
            path: dist

      - name: create image and store in Packages
        uses: mattdavis0351/actions/docker-gpr@1.3.0
        with:
            repo-token: ${{secrets.GITHUB_TOKEN}}
            image-name: ${{env.DOCKER_IMAGE_NAME}}
            tag:  
