name: Staging deployment

on: [pull_request,push]
env:
  LOG_LEVEL: info
  PORT: 3000
  NODE_ENV: test
  MONGO_DB: loubou97_notesdb
  DOCKER_IMAGE_NAME: loubou97/noteapp
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  DOCKER_IMAGE_TAG: latest
jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: npm install
          run: |
            npm install
        - name: npm run test
          run: |
            npm run test
        - name: npm run lint
          run: |
            npm run lint
        - name: npm run compile
          run: |
            npm run compile
        - uses: actions/upload-artifact@master
          with:
            name: dist aritiact
            path: dist/
  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: Build
    name: Build image and store in Github Packages
    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: download artifact
        uses: actions/download-artifact@master
        with:
            name: dist aritiact
            path: dist/
      - name: ls -l
        run:  ls -l 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{env.DOCKER_IMAGE_NAME}}:${{env.DOCKER_IMAGE_TAG}}
          
